# Generated by Django 3.1.7 on 2021-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
