# Generated by Django 3.1.7 on 2021-02-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210225_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('delivery', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
